# Created by Nelson Durrant, Feb 2025
ekf_filter_node_odom:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true # for now
    print_diagnostics: true
    debug: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: dvl/odometry
    odom0_config: [true, true, true,
                  true, true, true,
                  false, false,  false,
                  false, false, false,
                  false, false, false]
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10

    use_control: false

ekf_filter_node_map:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true # for now
    print_diagnostics: true
    debug: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    odom0: dvl/odometry
    odom0_config: [true, true, false,
                  false, false, true,
                  false, false,  false,
                  false, false, false,
                  false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: true

    odom1: odometry/gps
    odom1_config: [true,  true,  false,
                  false, false, true,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom1_queue_size: 10
    odom1_differential: false
    odom1_relative: false

    use_control: false

navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 3.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_utm_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: true
    wait_for_datum: true # set by the sync_origin node
