### ekf config file ###
#the below line will be automatically configured by factor launch to namespace/ekf_node:
/coug1/ekf_node:
        ros__parameters:
                frequency: 30.0


                two_d_mode: true


                publish_acceleration: false


                debug: true
                debug_out_file: /home/frostlab/ekf_debug.txt

                publish_tf: true

                map_frame: map       
                odom_frame: odom       
                base_link_frame: coug1.robot  
                world_frame: odom          

                pose0: dvl/dead_reckoning
                pose0_config: [true,true,false,
                                true,true,true,
                                false,false,false,
                                false,false,false,
                                false,false,false]

                # pose1: depth_data
                # pose1_config: [false,false,true,
                #                 false,false,false,
                #                 false,false,false,
                #                 false,false,false,
                #                 false,false,false]
                odom0: gps_odom
                odom0_config: [true,true,false,
                                false,false,false,
                                false,false,false,
                                false,false,false,
                                false,false,false]

                imu0: modem_imu
                imu0_config: [false, false, false,
                                false, false, false,
                                true, true, true,
                                true, true, true,
                                true, true, true]
                